name: Publish the built javascript to Github Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        tag:
          - main
          - 2.3.1
          - 2.4.0
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.tag }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build assets
        run: |
          npm run build -- --env tag=${{ matrix.tag }}
          ls dist/${{ matrix.tag }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.tag }}
          path: dist
  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gather builds
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Debugging
        run: |
          ls dist
      - name: Move the default build
        run: mv dist/main/* dist/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
